version: "3.9"

services:
  currency-api:
    build:
      context: .
      dockerfile: ./CurrencyService.Api/Dockerfile
    container_name: currency-api
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - seq

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin123
    ports:
      - "5341:5341"
      - "5342:80"
    volumes:
      - seq_data:/data

volumes:
  seq_data:
