name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE: myorg/currency-api

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore CurrencyService.Api/CurrencyService.Api.csproj

      - name: Build project
        run: dotnet build CurrencyService.Api/CurrencyService.Api.csproj --configuration Release --no-restore

      - name: Run tests & collect coverage
        run: dotnet test CurrencyService.Tests/CurrencyService.Tests.csproj --configuration Release --no-build --collect:"XPlat Code Coverage"

      - name: Publish Docker image
        run: docker build -t $DOCKER_IMAGE:latest -f CurrencyService.Api/Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:${{ github.sha }}
          docker push $DOCKER_IMAGE:latest
          docker push $DOCKER_IMAGE:${{ github.sha }}
